BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no
AUDIO_ENABLE = no
# TRACK_BALL_ENABLE = no
# POINTING_DEVICE_ENABLE = no
# PIMORONI_TRACKBALL_ENABLE = no
# POINTING_DEVICE_DRIVER = pimoroni_trackball
# SPLIT_KEYBOARD = yes

# ifeq ($(strip $(PIMORONI_TRACKBALL_ENABLE)), yes)
#     # SRC += pimoroni_trackball.c
#     POINTING_DEVICE_ENABLE := yes
# endif